# Generated by Django 3.0.2 on 2020-01-29 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo_gallery', '0002_album_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='album',
            name='lon',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='lon',
        ),
    ]
