# Generated by Django 3.0.2 on 2020-01-29 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_gallery', '0003_auto_20200129_1840'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='lliked_by',
            new_name='liked_by',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='lliked_by',
            new_name='liked_by',
        ),
        migrations.AlterField(
            model_name='album',
            name='link',
            field=models.URLField(blank=True),
        ),
    ]
