# Generated by Django 3.0.2 on 2020-01-30 17:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('photo_gallery', '0004_auto_20200129_1850'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='liked_by',
            new_name='likes',
        ),
        migrations.RemoveField(
            model_name='album',
            name='liked_by',
        ),
        migrations.AddField(
            model_name='album',
            name='lat',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='album',
            name='likes',
            field=models.ManyToManyField(related_name='liked_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='album',
            name='lon',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='album',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='owned_by', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photo',
            name='lat',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='lon',
            field=models.FloatField(null=True),
        ),
    ]
